// File: PageTwo.jsx
import ContentPageTemplate from './ContentPageTemplate';
import img1 from '../assets/img1.png';
import img2 from '../assets/img2.png';
import math from '../assets/math2.png';
import math2 from '../assets/math3.png';
import math4 from '../assets/math4.png';
import math5 from '../assets/math5.png';
import math6 from '../assets/math6.png';
import math7 from '../assets/math7.png';
import math8 from '../assets/math8.png';
import math9 from '../assets/math9.png';
function PageEleven() {
  const contentProps = {
    title: "Rocket Science: Where Momentum Takes Off!",
    header: "Conservation of Momentum",
    paragraphs: [
      "Rockets beautifully demonstrate Momentum Conservation. As the rocket pushes exhaust gases in one direction, it gains momentum in the opposite direction, propelling itself forward. Imagine two masses connected by a lightweight, compressed spring. When the spring is released, the masses move apart. According to the conservation of momentum, the total momentum before and after the spring is released stays the same, with the center of mass remaining in place or moving as it was.",
      "In mathematical terms:",
      {
        src: math,
        size: "full",
        alt: "Formula"
      },
      "The rocket does something similar. The rocket sends mass (exhaust gases) in one direction, causing the rocket to gain momentum in the opposite direction. Instead of ejecting a single chunk of mass, the rocket burns fuel continuously. This \"continuous\" burning is where calculus comes into play.",
      "The rocket’s velocity change over time can be described as:",
      {
        src: math2,
        size: "full",
        alt: "Formula"
      },
     "The thrust generated by the rocket is:",
     {
        src: math4,
        size: "full",
        alt: "Formula"
      },
      "Now, let’s break down how this works in detail:",
      "Consider a rocket moving at velocity (v) with mass M+dm. The rocket burns fuel, and the fuel leaves the rocket with exhaust speed ve. During a short period dt, the rocket burns fuel ∣dm∣, which decreases its mass.",
      "The initial momentum is:",
      {
        src: math5,
        size: "full",
        alt: "Formula"
      },
      "After burning the fuel, the rocket's velocity increases to v+dv, and its mass decreases to mmm. The final momentum is:",
      {
        src: math6,
        size: "full",
        alt: "Formula"
      },
      "Since momentum is conserved, we set the initial and final momentum equal:",
      {
        src: math7,
        size: "full",
        alt: "Formula"
      },
      "Since mass is decreasing, dm is negative (dm<0):",
      {
        src: math8,
        size: "full",
        alt: "Formula"
      },
      "Now, to integrate this, we treat vev_eve​ (the exhaust velocity) as a constant.",
      "Finally, we get:",
      {
        src: math9,
        size: "full",
        alt: "Formula"
      },
      "This equation tells us how the rocket’s velocity increases as fuel is burned and mass decreases. And of course, since Mi>Mf​, the natural log will be positive, meaning the final velocity will be greater than the initial velocity—just as we expect in a rocket launch."
    ],
    references: [
      {
        url: "https://www.ux1.eiu.edu/~addavis/1350/09Mom/Rock.html",
        text: "Davis, D. (2001). Rocket propulsion. Eastern Illinois University. ",
      },
    ],
    images: [img1, img2],
        imagePositions: {
          img1: 'top-left',
          img2: 'bottom-right'
        }
  };

  return <ContentPageTemplate {...contentProps} />;
}

export default PageEleven;
